
package poo.PL2.Interface;

import java.awt.Font;
import java.awt.Image;
import javax.swing.*;
import java.awt.event.*;
import poo.PL2.Clases.Carrito;
import poo.PL2.Clases.CarritoManager;
import poo.PL2.Clases.Cliente;
import poo.PL2.Clases.Navegacion;


public class PortalCliente extends javax.swing.JFrame {
    
    private final Cliente cliente;
    
    
    public PortalCliente(Cliente cliente) {
        initComponents();
        configurarComponentes();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null); // Centra la ventana
        this.cliente = cliente;
        
        Navegacion.ponerLogo(jLabelJavaEvents, jLabelJavaEvents1);
        
        // CREAR EL BOTÓN DE CARRITO
        JLabel iconLabel = new JLabel();
        
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/carrito.png"));

        Image imagenEscalada = icono.getImage()
        .getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        iconLabel.setIcon(new ImageIcon(imagenEscalada));

        jButtonCarrito.add(iconLabel);
        
        // Quitar el borde y fondo para que solo se vea el ícono
        jButtonCarrito.setBorderPainted(false);
        jButtonCarrito.setContentAreaFilled(false);
        jButtonCarrito.setFocusPainted(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBuscarEvento = new javax.swing.JButton();
        jButtonMisEventos = new javax.swing.JButton();
        jButtonMisDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonCarrito = new javax.swing.JButton();
        jLabelJavaEvents = new javax.swing.JLabel();
        jLabelJavaEvents1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBuscarEvento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBuscarEvento.setText("BUSCAR EVENTO");
        jButtonBuscarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarEventoActionPerformed(evt);
            }
        });

        jButtonMisEventos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonMisEventos.setText("MIS EVENTOS");
        jButtonMisEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMisEventosActionPerformed(evt);
            }
        });

        jButtonMisDatos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonMisDatos.setText("MIS DATOS");
        jButtonMisDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMisDatosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MI PORTAL");

        jButtonCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCerrarSesion.setForeground(new java.awt.Color(153, 0, 51));
        jButtonCerrarSesion.setText("CERRAR SESIÓN");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jButtonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuscarEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMisEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMisDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCarrito)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelJavaEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJavaEvents1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabelJavaEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelJavaEvents1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButtonCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButtonBuscarEvento)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButtonMisEventos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButtonMisDatos)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButtonCerrarSesion)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarComponentes() {
        jButtonCarrito.setToolTipText("Click para ir al carrito"); 
        
        UIManager.put("ToolTip.font", new Font("Arial", Font.BOLD, 12));  // Fuente personalizada
    }
    
    
    private void jButtonBuscarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEventoActionPerformed
        // TODO add your handling code here:
        Navegacion.cambiarVentana(this, new BuscarEvento(cliente)); // Buscar Evento
    }//GEN-LAST:event_jButtonBuscarEventoActionPerformed

    private void jButtonMisEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMisEventosActionPerformed
        // TODO add your handling code here:
        // Crear el popup menu
        JPopupMenu popupMenu = new JPopupMenu();
        
        // Crear las opciones
        JMenuItem itemReservados = new JMenuItem("EVENTOS RESERVADOS");
        JMenuItem itemAtendidos = new JMenuItem("EVENTOS ATENDIDOS");
        
        // Añadir acciones a las opciones
        itemReservados.addActionListener(e -> {
            Navegacion.cambiarVentana(this, new ConsultarEventosReservados(cliente));
        });

        itemAtendidos.addActionListener(e -> {
            Navegacion.cambiarVentana(this, new ConsultarEventosAtendidos(cliente));
        });
        
        // Agregar ítems al menú
        popupMenu.add(itemReservados);
        popupMenu.add(itemAtendidos);
        
        // Mostrar el popup en la posición del botón
        popupMenu.show(jButtonMisEventos, 3, jButtonMisEventos.getHeight());
    }//GEN-LAST:event_jButtonMisEventosActionPerformed

    private void jButtonMisDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMisDatosActionPerformed
        // TODO add your handling code here:
        Navegacion.cambiarVentana(this, new ModificarDatos(cliente)); // Mis Datos
    }//GEN-LAST:event_jButtonMisDatosActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Sesión cerrada con éxito");
        Navegacion.cambiarVentana(this, new MainMenu()); // Cerrar Sesión
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jButtonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarritoActionPerformed
        // TODO add your handling code here:
        Carrito carrito = CarritoManager.getCarrito(cliente);
        if (carrito.getItems().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "El carrito está vacío", 
                "Carrito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Navegacion.cambiarVentana(this, new CarritoCliente(cliente));
        }
    }//GEN-LAST:event_jButtonCarritoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarEvento;
    private javax.swing.JButton jButtonCarrito;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonMisDatos;
    private javax.swing.JButton jButtonMisEventos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelJavaEvents;
    private javax.swing.JLabel jLabelJavaEvents1;
    // End of variables declaration//GEN-END:variables
}
